ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    development: true
    deployment:
        port: 8080
        watch:
            - classes
            - resources
jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"


# Job queue sized to HikariCP connection pool
database.dispatcher:
    executor: "thread-pool-executor"
    throughput: 1
    thread-pool-executor:
        fixed-pool-size: 9

storage:
    # Set Hikari to fixed size
    prototype:
        hikaricp.minimumIdle: 9
        hikaricp.maximumPoolSize: 9