ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    development: true
    deployment:
        port: 8080
        watch:
            - classes
jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "ktor sample app"
